### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by bladerunner2020** [Trakkasure/mikronode#16]
I got strange behaviour. I have been using mikronode v0.3.3 from npm.
I have few applications that has the same code:

`var connection = new mikrotik(ip, login, pass);
  connection.connect(function(conn) {
         var chan = conn.openChannel();
...
}
`

They work fine, but sometime some application stopped working with an error (see below).
The same code in other applications continues to work.
It crashes when openChannel() is called.

`1 Apr 09:11:52 - [red] Uncaught Exception:
1 Apr 09:11:52 - Error: Uncaught, unspecified "error" event. (Timeout Connecting to host)
    at Connection.emit (events.js:157:17)
    at null.<anonymous> (/Users/Bladerunner/.node-red/node_modules/node-red-contrib-mikrotik/node_modules/mikronode/lib/index.js:458:55)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at Socket.<anonymous> (/Users/Bladerunner/.node-red/node_modules/node-red-contrib-mikrotik/node_modules/mikronode/lib/index.js:341:18)
    at Socket.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at Socket.emit (events.js:179:7)
    at Socket._onTimeout (net.js:326:8)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)`

**Comment by bladerunner2020** [comment]
Ok. I found the issue. This exception is thrown if it cannot connect (unavailable host or incorrect login).
How I can deal with this error in v0.3.3? In v1.x the exception is processed correctly.

**Comment by bladerunner2020** [comment]
Ok. I found the solution - needed to add error handler like this:
`var connection = new mikrotik(ip, login, pass); 
connection.on('error', function(err) {.... do something...});
connection.connect(function(conn) { 
var chan = conn.openChannel(); ... } `
