### ISSUE TITLE
mikronode@2.0.0-beta.4 can't be found after install using npm

### ISSUE THREAD

**Issue by leapon** [Trakkasure/mikronode#24]
mikronode@2.0.0-beta.4 can't be found after install vis npm

```
$ node -v
v6.6.0

$ npm install mikronode
symbol-observable@1.0.2 node_modules/mikronode/node_modules/rxjs/node_modules/symbol-observable -> node_modules/symbol-observable
rxjs@5.0.0-beta.12 node_modules/mikronode/node_modules/rxjs -> node_modules/rxjs
router@1.0.0 /Users/yliu0/git/trepity/router
└── mikronode@2.0.0-beta.4 
npm WARN router@1.0.0 No description
npm WARN router@1.0.0 No repository field.

$ ls node_modules/
mikronode		rxjs			symbol-observable

$ node
> var api = require('mikronode');
Error: Cannot find module 'mikronode'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
```

**Comment by leapon** [comment]
Tested on node 0.10 / 4.x / 6.x, all have same problem.

**Comment by Trakkasure** [comment]
Sorry about that... and for the long wait.
Package.json was pointing to index.js instead of mikronode.js

**Comment by leapon** [comment]
Got same error using beta.5

```

$ npm install --save mikronode
testabc@1.0.0 /Users/yliu0/git/testabc
└─┬ mikronode@2.0.0-beta.5 
  └─┬ rxjs@5.0.0-rc.1 
    └── symbol-observable@1.0.4 

$ ls -b node_modules/
mikronode		rxjs			symbol-observable

$ node
> var api = require('mikronode');
Error: Cannot find module 'mikronode'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
```
