### ISSUE TITLE
mikronode@2.0.0-beta.5 can't be found after install using npm

### ISSUE THREAD

**Issue by leapon** [Trakkasure/mikronode#25]
This is a follow up on https://github.com/Trakkasure/mikronode/issues/24

Got same error using beta.5. Please take a look. Thanks.

```
$ npm install --save mikronode
└─┬ mikronode@2.0.0-beta.5 
  └─┬ rxjs@5.0.0-rc.1 
    └── symbol-observable@1.0.4 

$ ls -b node_modules/
mikronode       rxjs            symbol-observable

$ node
> var api = require('mikronode');
Error: Cannot find module 'mikronode'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
```

**Comment by Trakkasure** [comment]
Fixed. removed dist from .npmignore.
use 2.0.0-beta.6

**Comment by leapon** [comment]
Thanks. It works!
