### ISSUE TITLE
Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by natanmedeiros** [Trakkasure/mikronode#34]
While doing the example...

                  var chan1=conn.openChannel("interface_listener");
                    chan1.write('/interface/listen');
                    chan1.read.subscribe(function(item) {
                        var packet=mod.apiMikrotik.resultsToObj(item.data);
                        console.log('Interface change: '+JSON.stringify(packet));
                    });

I had this mistake...

    erro TypeError: Cannot read property 'subscribe' of undefined
    at /var/www/html/sistema/sockets/controllers/mikrotik.js:288:31
    at tryCallOne (/var/www/html/sistema/sockets/node_modules/mikronode/dist/mikronode.js:665:13)
    at /var/www/html/sistema/sockets/node_modules/mikronode/dist/mikronode.js:751:16
    at flush (/var/www/html/sistema/sockets/node_modules/mikronode/dist/mikronode.js:897:30)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback `(internal/process/next_tick.js:128:9)

Can you help me fix it?

**Comment by Trakkasure** [comment]
try: chan1.data.subscribe(...)
