### ISSUE TITLE
parameter '= count-only =' does not return response

### ISSUE THREAD

**Issue by leo-combes** [Trakkasure/mikronode#60]
Seems to be same problem as described in #12.
When I make an API request through mikronode with ["/ip/address/print", "=count-only="] as parameter to chat.write it does no returns any value.

API request with just "/ip/address/print" returns proper results. I have tested with ipCountOnly.js example in node v6.10.3.

**Comment by Trakkasure** [comment]
Working on this. It seems that this might have been there. Running this test on earlier versions have the same result. Working to have something by tonight.

**Comment by Trakkasure** [comment]
This should resolve your issue. Let me know if you find anything else.

**Comment by leo-combes** [comment]
It seems that it does not work correctly.
Testing with the example `mikronode/examples/testCount.js`

If I use:
`channel1.write('/ip/address/print',{'=count-only=':''}).then(data=>{`

it returns:
`Done {"cmd":{"id":1,"command":"/ip/address/print","args":{"=count-only=":""}},"tag":1509909019974,"data":["2"]}`

and with mikrotik console:
```
ppp active print count-only
22
```
Mikronode return "2" and console "22".

Another test:
`channel1.write('/ppp/active/print',{'=count-only=':''}).then(data=>{`

it returns:
`Done {"cmd":{"id":1,"command":"/ppp/active/print","args":{"=count-only=":""}},"tag":1509909154511,"data":["1"]}`

with mikrotik console:
```
ppp active print count-only
10
```
Mikronode return "1" and console "10" or "2" and "22". Could be that is missing a number?

Querying without "count" seems be worst:
`channel1.write('/ip/address/print').then(data=>{`

```
/test/node_modules/mikronode/dist/mikronode.js:2289
                  throw err;
                  ^

TypeError: Cannot read property '0' of undefined
    at MergeMapSubscriber.project (/test/node_modules/mikronode/dist/mikronode.js:23048:33)
    at MergeMapSubscriber._tryNext (/test/node_modules/mikronode/dist/mikronode.js:9490:28)
    at MergeMapSubscriber._next (/test/node_modules/mikronode/dist/mikronode.js:9480:19)
    at MergeMapSubscriber.Subscriber.next (/test/node_modules/mikronode/dist/mikronode.js:2184:19)
    at DoSubscriber._next (/test/node_modules/mikronode/dist/mikronode.js:11070:31)
    at DoSubscriber.Subscriber.next (/test/node_modules/mikronode/dist/mikronode.js:2184:19)
    at TakeWhileSubscriber.nextOrComplete (/test/node_modules/mikronode/dist/mikronode.js:16809:26)
    at TakeWhileSubscriber._next (/test/node_modules/mikronode/dist/mikronode.js:16804:15)
    at TakeWhileSubscriber.Subscriber.next (/test/node_modules/mikronode/dist/mikronode.js:2184:19)
    at FilterSubscriber._next (/test/node_modules/mikronode/dist/mikronode.js:11763:31)
    at FilterSubscriber.Subscriber.next (/test/node_modules/mikronode/dist/mikronode.js:2184:19)
    at RefCountSubscriber.Subscriber._next (/test/node_modules/mikronode/dist/mikronode.js:2220:27)
    at RefCountSubscriber.Subscriber.next (/test/node_modules/mikronode/dist/mikronode.js:2184:19)
    at Subject.next (/test/node_modules/mikronode/dist/mikronode.js:1776:26)
    at ConnectableSubscriber.Subscriber._next (/test/node_modules/mikronode/dist/mikronode.js:2220:27)
    at ConnectableSubscriber.Subscriber.next (/test/node_modules/mikronode/dist/mikronode.js:2184:19)
```

**Comment by Trakkasure** [comment]
Ok. Test the master branch. This was an oversight since I didn't have more than 3 IP addresses. Testing with my DHCP server resolved to the correct content.
I'll publish to NPM when you let me know it's working. Although I believe I've fixed it.

**Comment by leo-combes** [comment]
It seems that it is a project to compile with babel and webpack, I have no experience with this.
I have installed mikronode from npm and use it with node.js from a file in dist/mikronode.js
How should I do to build the file mikronode.js from the src directory of git repository?

**Comment by Trakkasure** [comment]
git clone repoaddress
npm run build
(that gives you everything in the "dist" folder.)
npm link
cd to your project folder
npm link mikronode

now you should be able test your application with a built version from git.

**Comment by leo-combes** [comment]
I think I almost have it.
But now it seems that a parser.js file is missing:

ERROR in ./src/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./parser.js in /var/www/desemax2/wampServer/mikronode/src
 @ ./src/index.js 55:14-36

**Comment by leo-combes** [comment]
I did not try it massively, but in the same tests mentioned above it worked perfect!
