### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bgobi1991** [Trakkasure/mikronode#7]
Hi Team,

I got following error,

if (d.length<1) return;
                         ^

TypeError: Cannot read property 'length' of undefined
    at Socket.loginHandler (D:\examples\mysqlwatch\node_modules\mikronode\lib\index.js:385:26)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1045:10)

**Comment by mastepanoski** [comment]
I update this making two changes. First util.debug is deprecated, so I changed it for "console.error" in the whole JS.
Next, I modified "var Socket = require('net').Socket;" with this change: "var net = require('net');" And I modified de connect function: 

api.prototype.connect = function(connectHandler) {
    // While logging in, if an error occurs, we should kill the socket. This will keep node from not terminating due to lingering sockets.
    if (this.debug > 3) console.error('Connecting to ' + this.host);
    this.connecting = true;
    var self = this;
    this.socket = net.connect(this.port, this.host, connectHandler);
    // This will be called if there is no activity to the server.
    // If this occurs before the login is successful, it could be
    // that it is a connection timeout.
    this.socket.setTimeout(this.timeout * 1000, function(e) { // the socket timed out. According to the NodeJS api docs, right after this, it will be._closed.
      if (self.debug)
        console.error('Socket Timeout');
      if (!self.connected)
        self.emit('error', 'Timeout Connecting to host', self);
    });
    this.socket.setKeepAlive(true);
    this.socket.on('data', function(a) {
      self.read(a);
    });
    this.socket.on('end', function(a) {
      self.socket.destroy();
      if (self.connected)
        self.handler.close(true);
    });
    this.socket.on('error', function(a) {
      if (self.debug > 1)
        util.log('Connection error: ' + a);
      self.handler.emit('error', a, this.handler)
      self.handler.close(true);
    });
  }

**Comment by gtjoseph** [comment]
Do yo still get this error?  Can you try with the 1.X.X branch?

**Comment by mastepanoski** [comment]
I tried with de release branch (v1.0.3), and it worked. I am using it in a REST API (It was implemented in HapiJS) to manage several connection features and a lot of queries (around of 600 users). The 1.x.x version is a great work.

**Comment by gtjoseph** [comment]
Thanks!
