### ISSUE TITLE
How to catch errors on device.connect?

### ISSUE THREAD

**Issue by leo-combes** [Trakkasure/mikronode#70]
It seems that I can not find how to capture the errors on device.connect(), for example, in case the host is not available.

This is what I tried, nothing works:

function(err)
```
device.connect().then(([login])=>login('username','password')).then(function(conn) {
    // do stuff
},function(err) {
    console.log("Failed to connect. ",err);  // never reach here
});
```

device.on('error'...
```
device.on('error', function(err) {
    console.log("Failed to connect!");  // TypeError: device.on is not a function
});
```
...and other tests like this:
`device.connect().then(([login])=>login('username','password'), function(err){ console.log("Failed to connect!")}).then(function(conn){`

The documentation says:
Device.connect([cb]) Connect to the target device. The optional callback function is called after successful connect with the function to call to login as the 2nd parameter, and any connection errors as the first. the connect method returns a Promise that is resolved when connecting.

...but I don't understand how work.

Is any example for that?

**Comment by Trakkasure** [comment]
So, it is as simple as catching the rejection:

```javascript
device.connect()
    .then(([login])=>login('username','password'))
// Add .catch(err=>{}) here to catch only login exceptions.
    .then(function(conn) {
    // do stuff
})
// add .catch(err=>{}) to catch both login and exceptions in the "do stuff" section.

// Add both to capture login and "do stuff" sections separately.
```

**Comment by Trakkasure** [comment]
So, it is as simple as catching the rejection:

```javascript
device.connect()
    .then(([login])=>login('username','password'))
// Add .catch(err=>{}) here to catch only login exceptions.
    .then(function(conn) {
    // do stuff
})
// add .catch(err=>{}) to catch both login and exceptions in the "do stuff" section.

// Add both to capture login and "do stuff" sections separately.
```

**Comment by leo-combes** [comment]
I have tried this, but it does not work. No error message is displayed on the console.

```
var device = new MikroNode('10.0.140.140');
device.connect()
    .then(([login])=>login('username','password'))
    .catch(err=>{
        console.log("error");
    }).then(function(conn) {
        console.log("ok");
    }).catch(err=>{
        console.log("error");
    })
```
Remember that the error should show is the timeout, as the host 10.0.140.140 not available.

**Comment by Fibrewire** [comment]
Seconded, intentionally sending incorrect login credentials, no output to console, 

Node v8.4.0
Mikronode v2.3.7

```javascript
function runPingTest(test) {
	console.log(' JSON.parse(test.parameters).lns.ipv4:',JSON.parse(test.parameters).lns.ipv4);
	console.log('JSON.parse(test.parameters).lns.title:',JSON.parse(test.parameters).lns.title);
	var gateway = new MikroNode(JSON.parse(test.parameters).lns.ipv4);
	gateway.connect().then(([login]) => login('wrong','credentials')).catch(error => {
		console.log('HELLO?')
		logger.error("Unable to connect to "+JSON.parse(test.parameters).lns.title+" ("+JSON.parse(test.parameters).lns.ipv4+"),",MikroNode.resultsToObj(error).message);
		//checkForPendingPingTests();
	}).then(function(conn) {
		console.log('WORLD?')
		var channel1 = conn.openChannel();
		channel1.closeOnDone(true);
		channel1.write('/tools/ping',{address:JSON.parse(test.parameters).ipv4,count:3});
		channel1.data.subscribe(function(response) {
			console.dir(MikroNode.resultsToObj(response));
		});
		channel2.done.subscribe(function(response) {
			console.dir(MikroNode.resultsToObj(response));
			//completePingTest(test);
		});
	}).catch(error => {
		console.log('ANYTHING?')
		logger.error("Ping command failed,",MikroNode.resultsToObj(error).message);
		//checkForPendingPingTests();
	})
}
```

**Comment by Trakkasure** [comment]
What version of routeros/device-type are you connecting to?
I've tested the examples in the repo, and they work properly with incorrect credentials.
```bash
$ node examples/getInterfacesAndRoutes.js
Error connecting: [ { field: 'message', value: 'cannot log in' } ]
$
```
But that is with a correct IP address/port. With incorrect IP/port, it does what you are experiencing.

So, I believe I need to capture network errors and pass them on. I'll get that in ASAP.

**Comment by Fibrewire** [comment]
```
JSON.parse(test.parameters).lns.ipv4 = 93.190.116.14
```

can confirm 93.190.116.14 is on of our LNS's, 

![capture](https://user-images.githubusercontent.com/2836205/35628701-a55317fc-0694-11e8-8cb7-52f25e1d9fd7.PNG)
![capture2](https://user-images.githubusercontent.com/2836205/35628702-a6f7bef0-0694-11e8-9a36-33283a1a590d.PNG)

**Comment by AndyMeusel** [comment]
Looks good

```
93.190.116.14
16:30:40 <ERROR> Unable to connect to RBLNS3 - London (93.190.116.14), undefined (TEST.JS:59)
Call Stack:
    at gateway.connect.then.catch.error (C:\Users\AMeusel\Desktop\Diagnostics\ping\test.js:59:10)

    at tryCallOne (C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:774:13)
    at C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:860:16
    at flush (C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:1006:30)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
16:30:40 <ERROR> Ping command failed, undefined (TEST.JS:73)
Call Stack:
    at gateway.connect.then.catch.then.catch.error (C:\Users\AMeusel\Desktop\Diagnostics\ping\test.js:73:10)
    at tryCallOne (C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:774:13)
    at C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:860:16
    at flush (C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:1006:30)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by Trakkasure** [comment]
Cool. Closing

**Comment by AndyMeusel** [comment]
Code continues to execute after a connection error is caught

```
09:29:26 <ERROR> Unable to connect to RBLNS3 - London (93.190.116.1), connect ECONNREFUSED 93.190.116.1:8728 (TEST.JS:94)
Call Stack:
    at gateway.connect.then.catch.error (C:\Users\AMeusel\Desktop\Diagnostics\speed\test.js:94:10)
    at tryCallOne (C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:774:13)
    at C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:860:16
    at flush (C:\Users\AMeusel\Desktop\Diagnostics\node_modules\mikronode\dist\mikronode.js:1006:30)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
```
09:29:26  <WARN> /tool/bandwidth-test command failed, Cannot read property 'openChannel' of undefined (TEST.JS:117)
```

```javascript
function runSpeedTest(test) {
	var gateway = new MikroNode(JSON.parse(test.parameters).lns.ipv4);
	gateway.connect().then(([login]) => login('user','password'
	)).catch(error => {
		logger.error('Unable to connect to '+JSON.parse(test.parameters).lns.title+' ('+JSON.parse(test.parameters).lns.ipv4+'),',(error.message||JSON.stringify(error)));
        test.pass = 0;
        test.error = 1;
        test.response = JSON.stringify(error);
		completeSpeedTest(test);
	}).then(function(conn) {
		var channel1 = conn.openChannel();
		channel1.closeOnDone(true);
		channel1.write('/tool/bandwidth-test',{address:JSON.parse(test.parameters).ipv4,direction:'both',duration:'10s',protocol:'tcp',user:'user',password:'password'});
		channel1.done.subscribe(function(response) {
			if (MikroNode.resultsToObj(response.data[response.data.length-1]).status == 'done testing') {
	        	test.pass = 1;
	        	test.error = 0;
				test.response = JSON.stringify(MikroNode.resultsToObj(response.data[response.data.length-1]));
				completeSpeedTest(test);
			} else {
	        	test.pass = 0;
	        	test.error = 0;
				test.response = JSON.stringify(MikroNode.resultsToObj(response.data[response.data.length-1]));
				completeSpeedTest(test);
			}
        });
	}).catch(error => {
		logger.warn('/tool/bandwidth-test command failed,',(error.message||JSON.stringify(error)));
        test.pass = 0;
        test.error = 1;
        test.response = JSON.stringify(error);
		completeSpeedTest(test);
	});
}
```

**Comment by Trakkasure** [comment]
This is a *feature* of promises...
```javascript
promise.then(funcExecutedOnResolve) //<- Returns a promise.
promse.catch(funcToExecuteOnReject) //<- Returns a promise.
```
Return a rejected promise to skip the next then and go directly to the next catch.

Ultimately, if you want to branch your code, you can use promise branching by separating the then/catch sections.

```javascript
p = new Promise((resolve,reject)=>{ // do something});
p.then(onSuccessFunction)/*(promise)*/.then(onNextSuccessFunction);
p.catch(errorOccurred); // Nothing will execute next after catch fires.

var gateway = new MikroNode(JSON.parse(test.parameters).lns.ipv4);
var c = gateway.connect();
var l = c.then(([login]) => login('user','password'));
var run = l.then(function(conn) { 
	var channel1 = conn.openChannel();
	channel1.closeOnDone(true);
	channel1.write('/tool/bandwidth-test',{address:JSON.parse(test.parameters).ipv4,direction:'both',duration:'10s',protocol:'tcp',user:'user',password:'password'});
	channel1.done.subscribe(function(response) {
		if (MikroNode.resultsToObj(response.data[response.data.length-1]).status == 'done testing') {
        		test.pass = 1;
        		test.error = 0;
			test.response = JSON.stringify(MikroNode.resultsToObj(response.data[response.data.length-1]));
			completeSpeedTest(test);
		} else {
	        	test.pass = 0;
	        	test.error = 0;
			test.response = JSON.stringify(MikroNode.resultsToObj(response.data[response.data.length-1]));
			completeSpeedTest(test);
		}
        });
}) // End of your bandwidth test code

// If either connect or login fail, emit error for specific error, return error, and clean up in then()
Promise.race([
	c.catch(error => {
		logger.error('Unable to connect to '+JSON.parse(test.parameters).lns.title+' ('+JSON.parse(test.parameters).lns.ipv4+'),',(error.message||JSON.stringify(error)));
	}),
	l.catch(error => {
		logger.error('Unable to login to '+JSON.parse(test.parameters).lns.title+' ('+JSON.parse(test.parameters).lns.ipv4+'),',(error.message||JSON.stringify(error)));
	}),
	run.catch(error => { // Handle error on bandwidth test code.
		logger.warn('/tool/bandwidth-test command failed,',(error.message||JSON.stringify(error)));
	})
]).then(error=>{
        test.pass = 0;
        test.error = 1;
        test.response = JSON.stringify(error);
        completeSpeedTest(test);
});

**Comment by AndyMeusel** [comment]
Thanks Brandon
