### ISSUE TITLE
Printing arp produces an error

### ISSUE THREAD

**Issue by Subash** [Trakkasure/mikronode#81]
`channel.write('/ip/arp/print')`

```shell
***************************************************************************
***************************************************************************
Error processing sentence: { SyntaxError: Expected [.a-z\-0-9] but "D" found.
    at peg$buildStructuredError (/Users/subash/Projects/lan-manager/node_modules/mikronode/dist/mikronode.js:2166:13)
    at Object.peg$parse [as parse] (/Users/subash/Projects/lan-manager/node_modules/mikronode/dist/mikronode.js:3193:12)
    at MapSubscriber.project (/Users/subash/Projects/lan-manager/node_modules/mikronode/dist/mikronode.js:478:39)
    at MapSubscriber._next (/Users/subash/Projects/lan-manager/node_modules/rxjs/operators/map.js:79:35)
    at MapSubscriber.Subscriber.next (/Users/subash/Projects/lan-manager/node_modules/rxjs/Subscriber.js:93:18)
    at MapSubscriber._next (/Users/subash/Projects/lan-manager/node_modules/rxjs/operators/map.js:85:26)
    at MapSubscriber.Subscriber.next (/Users/subash/Projects/lan-manager/node_modules/rxjs/Subscriber.js:93:18)
    at DoSubscriber._next (/Users/subash/Projects/lan-manager/node_modules/rxjs/operators/tap.js:88:30)
    at DoSubscriber.Subscriber.next (/Users/subash/Projects/lan-manager/node_modules/rxjs/Subscriber.js:93:18)
    at Subject.next (/Users/subash/Projects/lan-manager/node_modules/rxjs/Subject.js:55:25)
  message: 'Expected [.a-z\\-0-9] but "D" found.',
  expected:
   [ { type: 'class',
       parts: [Array],
       inverted: false,
       ignoreCase: false } ],
  found: 'D',
  location:
   { start: { offset: 164, line: 9, column: 2 },
     end: { offset: 165, line: 9, column: 3 } },
  name: 'SyntaxError' }
Skipping and continuing
```

**Comment by Subash** [comment]
Never-mind, fixed by updating to the latest version.

**Comment by Subash** [comment]
Nevermind, fixed by updating to the latest version.
