### ISSUE TITLE
Problem with log in 

### ISSUE THREAD

**Issue by xeleniumz** [Trakkasure/mikronode#82]
i don't know what's happen when i try to connect with your example code here is an error.
node version 8.11.3
routeros version 6.40.3

`Unhandled rejection:  {}
 Promise {
  <rejected> TypeError: _sentence$.get(...).do is not a function
    at new SocketStream (/var/www/zcm/node_modules/mikronode/dist/mikronode.js:474:52)
    at MikroNode.connect (/var/www/zcm/node_modules/mikronode/dist/mikronode.js:330:30)
    at _callee5$ (/var/www/zcm/app/controllers/api.controller.js:161:24)
    at tryCatch (/var/www/zcm/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/var/www/zcm/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/var/www/zcm/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/var/www/zcm/app/controllers/api.controller.js:31:191)
    at /var/www/zcm/app/controllers/api.controller.js:31:361
    at <anonymous> }`

**Comment by xeleniumz** [comment]
fixed it by install rxjs lastest version
