### ISSUE TITLE
_sentence$.get(...).do is not a function

### ISSUE THREAD

**Issue by LaKing** [Trakkasure/mikronode#93]
I'm trying to run the main example, and get:

```
/home/x/mikrotik/node_modules/mikronode/dist/mikronode.js:474
	        _parsed$.set(this, _sentence$.get(this).do(function (d) {
	                                                  ^

TypeError: _sentence$.get(...).do is not a function
    at new SocketStream (/home/x/mikrotik/node_modules/mikronode/dist/mikronode.js:474:52)
    at MikroNode.connect (/home/x/mikrotik/node_modules/mikronode/dist/mikronode.js:330:30)
    at Object.<anonymous> (/home/x/mikrotik/grab.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

```

**Comment by adams-family** [comment]
Any update on this?

**Comment by adams-family** [comment]
Ok the initial problem solved by installing an EARLIER version of rxjs thanks to this post:

https://stackoverflow.com/questions/51727130/mikronode-with-express-js-typeerror-sentence-get-do-is-not-a-function#52114073

Just modified dependencies in my package.json as follows:

  "dependencies": {
    "core-decorators": "^0.20.0",
    "mikronode": "^2.3.11",
    "rxjs": "^5.3.0"
  }

However, still no luck with login :( I'm afraid that this package is not working at the moment.
