### ISSUE TITLE
Writing ip/hotspot/print results in  SyntaxError: Expected [.a-z\-0-9] but "H" found

### ISSUE THREAD

**Issue by AndyMeusel** [Trakkasure/mikronode#94]
Packet received:  [ '\u0003!re\u0011.tag=1-channel1-2\u0007=.id=*1\r=name=hotspot\u0012=interface=Hotspot\u0018=address-pool=hs-pool-33\u0010=profile=hsprof1\u0010=idle-timeout=5m\u0017=keepalive-timeout=none\u0013=login-timeout=none\u0014=addresses-per-mac=1\u001f=ip-of-dns-name=0.0.0.0\u0015=proxy-status=running\u000e=invalid=false\u000b=HTTPS=true\u000f=disabled=false',
  '\u0005!done\u0011.tag=1-channel1-2',
  '' ]
***************************************************************************
***************************************************************************
Error processing sentence: { SyntaxError: Expected [.a-z\-0-9] but "H" found.
    at peg$buildStructuredError (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\mikronode\dist\mikronode.js:2164:13)
    at Object.peg$parse [as parse] (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\mikronode\dist\mikronode.js:3191:12)
    at MapSubscriber.project (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\mikronode\dist\mikronode.js:476:39)
    at MapSubscriber._next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\operators\map.js:79:35)
    at MapSubscriber.Subscriber.next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\Subscriber.js:90:18)
    at MapSubscriber._next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\operators\map.js:85:26)
    at MapSubscriber.Subscriber.next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\Subscriber.js:90:18)
    at DoSubscriber._next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\operators\tap.js:88:30)
    at DoSubscriber.Subscriber.next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\Subscriber.js:90:18)
    at Subject.next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\Subject.js:55:25)
    at ScanSubscriber.accumulator (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\mikronode\dist\mikronode.js:519:41)
    at ScanSubscriber._tryNext (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\operators\scan.js:111:27)
    at ScanSubscriber._next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\operators\scan.js:104:25)
    at ScanSubscriber.Subscriber.next (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\Subscriber.js:90:18)
    at Socket.handler (C:\Users\AMeusel\Documents\GitHub\portal.liberty-izone.com\node_modules\rxjs\observable\FromEventObservable.js:210:46)
    at emitOne (events.js:115:13)
  message: 'Expected [.a-z\\-0-9] but "H" found.',
  expected:
   [ { type: 'class',
       parts: [Array],
       inverted: false,
       ignoreCase: false } ],
  found: 'H',
  location:
   { start: { offset: 257, line: 15, column: 2 },
     end: { offset: 258, line: 15, column: 3 } },
  name: 'SyntaxError' }
Skipping and continuing
***************************************************************************
***************************************************************************

**Comment by AndyMeusel** [comment]
This is a duplicate of https://github.com/Trakkasure/mikronode/issues/75 but it went unresolved

**Comment by AndyMeusel** [comment]
Apologies, #75 was resolved, I am running a few versions behind
